# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-18 18:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('polyline', models.TextField()),
                ('distance', models.FloatField()),
                ('start_lat', models.CharField(max_length=100)),
                ('start_long', models.CharField(max_length=100)),
                ('finish_lat', models.CharField(max_length=100)),
                ('finish_long', models.CharField(max_length=100)),
                ('min_elevation', models.FloatField()),
                ('max_elevation', models.FloatField()),
                ('elevation_gain', models.FloatField()),
                ('difficulty', models.CharField(choices=[('EA', 'Easy'), ('MO', 'Moderate'), ('TO', 'Tough')], max_length=2)),
                ('country', models.CharField(choices=[('GB', 'United Kingdom'), ('FR', 'France'), ('IT', 'Italy'), ('ES', 'Spain'), ('DE', 'Germany')], max_length=2)),
                ('locality', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=None, verbose_name='date published')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
