# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-22 19:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0011_auto_20171122_1930'),
        ('routes', '0002_auto_20171001_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='challenger',
            field=models.ManyToManyField(related_name='challenger', through='challenges.Participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
