# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-18 01:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_route_challenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='challenger',
        ),
    ]
