# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0002_auto_20170310_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_organiser',
            field=models.BooleanField(default=False),
        ),
    ]
