# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-22 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengetime',
            name='challenges',
            field=models.ManyToManyField(default=None, to='challenges.Challenge'),
        ),
    ]
