# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-29 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_challengetime_challenges'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengetime',
            name='performance',
            field=models.FloatField(default=None),
        ),
    ]
