# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-30 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_challengetime_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengetime',
            name='is_performance_negative',
            field=models.BooleanField(default=False),
        ),
    ]
