# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-30 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_challengetime_is_performance_negative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengetime',
            name='is_performance_negative',
        ),
    ]
