# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-06 00:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_challenge_target_time_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengetime',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
            preserve_default=False,
        ),
    ]
