# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-08 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_challengetime_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengetime',
            name='duration_str',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
