# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-22 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_remove_challenge_challenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengetime',
            name='challenges',
        ),
    ]
