# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-22 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0011_auto_20171122_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='completed_challenge',
        ),
        migrations.AddField(
            model_name='challenge',
            name='completed_challenge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challengetime',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.Challenge'),
        ),
        migrations.AddField(
            model_name='challengetime',
            name='hit_target',
            field=models.BooleanField(default=False),
        ),
    ]
