# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-27 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0012_auto_20171122_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='is_current_challenge',
            field=models.BooleanField(default=False),
        ),
    ]
