# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-18 01:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_remove_route_challenger'),
        ('challenges', '0014_auto_20171127_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='route',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='user',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='route',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='challengetime',
            name='challenge',
        ),
        migrations.DeleteModel(
            name='Challenge',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
